version: '3.9'

services:
  byte-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: byte-db
      POSTGRES_USER: mustty
      POSTGRES_PASSWORD: mypass132
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
